language: python
python:
  - "3.8"
# command to install dependencies
before_install:
  - "pip install -U pip"
  - "python setup.py install"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"

# install:
  #- pip install -r requirements
  #- pip install .
# command to run tests
script: pytest
